### ISSUE TITLE
Installation issue on clean Raspbian

### ISSUE THREAD

**Issue by pawelpoplawski** [CODAIT/node-red-contrib-model-asset-exchange#52]
Hi,

just tried to install the node straight on clean raspbian without a success.
Are there any prerequisites to get it installed?

**Comment by pawelpoplawski** [comment]
To be more specific package pixman-1 is missing

`019-04-30T10:22:41.635Z Install : node-red-contrib-model-asset-exchange 0.2.3

2019-04-30T10:22:41.679Z npm install --no-audit --no-update-notifier --save --save-prefix="~" --production node-red-contrib-model-asset-exchange@0.2.3
2019-04-30T10:22:59.732Z [out] 
2019-04-30T10:22:59.732Z [out] > canvas@2.4.1 install /home/pi/.node-red/node_modules/canvas
2019-04-30T10:22:59.732Z [out] > node-pre-gyp install --fallback-to-build
2019-04-30T10:22:59.732Z [out] 
2019-04-30T10:23:04.081Z [err] node-pre-gyp
2019-04-30T10:23:04.085Z [err]  
2019-04-30T10:23:04.086Z [err] WARN Using request for node-pre-gyp https download
2019-04-30T10:23:04.086Z [err]  
2019-04-30T10:23:04.994Z [err] node-pre-gyp WARN Tried to download(404): https://github.com/node-gfx/node-canvas-prebuilt/releases/download/v2.4.1/canvas-v2.4.1-node-v57-linux-glibc-arm.tar.gz 
2019-04-30T10:23:04.994Z [err] node-pre-gyp WARN Pre-built binaries not found for canvas@2.4.1 and node@8.11.1 (node-v57 ABI, glibc) (falling back to source compile with node-gyp) 
2019-04-30T10:23:22.714Z [err] Package pixman-1 was not found in the pkg-config search path.
2019-04-30T10:23:22.714Z [err] Perhaps you should add the directory containing `pixman-1.pc'
2019-04-30T10:23:22.714Z [err] to the PKG_CONFIG_PATH environment variable
2019-04-30T10:23:22.714Z [err] No package 'pixman-1' found
2019-04-30T10:23:22.714Z [err] gyp: Call to 'pkg-config pixman-1 --libs' returned exit status 1 while in binding.gyp. while trying to load binding.gyp
2019-04-30T10:23:22.764Z [err] gyp ERR! configure error 
2019-04-30T10:23:22.764Z [err] gyp ERR! stack Error: `gyp` failed with exit code: 1
2019-04-30T10:23:22.764Z [err] gyp ERR! 
2019-04-30T10:23:22.772Z [err] stack     at ChildProcess.onCpExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:345:16)
2019-04-30T10:23:22.772Z [err] gyp ERR! stack     at emitTwo (events.js:126:13)
2019-04-30T10:23:22.772Z [err] gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
2019-04-30T10:23:22.772Z [err] gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
2019-04-30T10:23:22.772Z [err] gyp ERR! System Linux 4.14.98-v7+
2019-04-30T10:23:22.772Z [err] gyp ERR! command "/usr/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "--fallback-to-build" "--module=/home/pi/.node-red/node_modules/canvas/build/Release/canvas.node" "--module_name=canvas" "--module_path=/home/pi/.node-red/node_modules/canvas/build/Release" "--napi_version=1" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=node-v57"
2019-04-30T10:23:22.772Z [err] gyp ERR! cwd /home/pi/.node-red/node_modules/canvas
2019-04-30T10:23:22.772Z [err] gyp ERR! node -v v8.11.1
2019-04-30T10:23:22.772Z [err] gyp ERR! node-gyp -v v3.8.0
2019-04-30T10:23:22.772Z [err] gyp ERR! not ok 
2019-04-30T10:23:22.783Z [err] node-pre-gyp
2019-04-30T10:23:22.784Z [err]  ERR! build error 
2019-04-30T10:23:22.786Z [err] node-pre-gyp
2019-04-30T10:23:22.786Z [err]  ERR! stack Error: Failed to execute '/usr/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/home/pi/.node-red/node_modules/canvas/build/Release/canvas.node --module_name=canvas --module_path=/home/pi/.node-red/node_modules/canvas/build/Release --napi_version=1 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v57' (1)
2019-04-30T10:23:22.786Z [err] node-pre-gyp
2019-04-30T10:23:22.786Z [err]  ERR! stack     at ChildProcess.<anonymous> (/home/pi/.node-red/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
2019-04-30T10:23:22.786Z [err] node-pre-gyp ERR!
2019-04-30T10:23:22.787Z [err]  stack     at emitTwo (events.js:126:13)
2019-04-30T10:23:22.787Z [err] node-pre-gyp ERR!
2019-04-30T10:23:22.787Z [err]  stack     at ChildProcess.emit (events.js:214:7)
2019-04-30T10:23:22.787Z [err] node-pre-gyp ERR!
2019-04-30T10:23:22.787Z [err]  stack     at maybeClose (internal/child_process.js:925:16)
2019-04-30T10:23:22.787Z [err] node-pre-gyp ERR!
2019-04-30T10:23:22.788Z [err]  stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
2019-04-30T10:23:22.789Z [err] node-pre-gyp
2019-04-30T10:23:22.789Z [err]  ERR! System Linux 4.14.98-v7+
2019-04-30T10:23:22.790Z [err] node-pre-gyp
2019-04-30T10:23:22.790Z [err]  
2019-04-30T10:23:22.790Z [err] ERR!
2019-04-30T10:23:22.791Z [err]  command "/usr/bin/node" "/home/pi/.node-red/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
2019-04-30T10:23:22.791Z [err] node-pre-gyp
2019-04-30T10:23:22.791Z [err]  ERR! cwd
2019-04-30T10:23:22.791Z [err]  /home/pi/.node-red/node_modules/canvas
2019-04-30T10:23:22.791Z [err] node-pre-gyp
2019-04-30T10:23:22.792Z [err]  ERR! 
2019-04-30T10:23:22.792Z [err] node -v v8.11.1
2019-04-30T10:23:22.792Z [err] node-pre-gyp ERR!
2019-04-30T10:23:22.792Z [err]  node-pre-gyp -v v0.11.0
2019-04-30T10:23:22.793Z [err] node-pre-gyp 
2019-04-30T10:23:22.793Z [err] ERR! not ok 
2019-04-30T10:23:22.794Z [out] Failed to execute '/usr/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/home/pi/.node-red/node_modules/canvas/build/Release/canvas.node --module_name=canvas --module_path=/home/pi/.node-red/node_modules/canvas/build/Release --napi_version=1 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v57' (1)
2019-04-30T10:23:23.852Z [err] npm ERR! code ELIFECYCLE
2019-04-30T10:23:23.853Z [err] npm ERR! errno 1
2019-04-30T10:23:23.861Z [err] npm
2019-04-30T10:23:23.862Z [err]  ERR! canvas@2.4.1 install: `node-pre-gyp install --fallback-to-build`
2019-04-30T10:23:23.862Z [err] npm ERR! Exit status 1
2019-04-30T10:23:23.863Z [err] npm ERR!
2019-04-30T10:23:23.863Z [err]  
2019-04-30T10:23:23.863Z [err] npm ERR! Failed at the canvas@2.4.1 install script.
2019-04-30T10:23:23.863Z [err] npm ERR!
2019-04-30T10:23:23.864Z [err]  This is probably not a problem with npm. There is likely additional logging output above.
2019-04-30T10:23:23.943Z [err] 
2019-04-30T10:23:23.944Z [err] npm ERR! A complete log of this run can be found in:
2019-04-30T10:23:23.944Z [err] npm
2019-04-30T10:23:23.945Z [err]  ERR!     /home/pi/.npm/_logs/2019-04-30T10_23_23_910Z-debug.log
2019-04-30T10:23:23.976Z rc=1`

**Comment by ptitzler** [comment]
Looks like this problem was introduced by the latest annotated image preview enhancement. Can you (for now) please try to install version 0.2.0?

**Comment by pawelpoplawski** [comment]
Works. 0.2.0 installed as expected.

**Comment by ptitzler** [comment]
We will replace the breaking dependency with another one that should work in all environments.

**Comment by kastentx** [comment]
@pawelpoplawski we've just published a new version `0.2.4` that got rid of the dependencies causing this error. 

You should now be able to install the most recent update and try out the new visualization features. Thanks for bringing this to our attention!
