### ISSUE TITLE
installation issues

### ISSUE THREAD

**Issue by martinschki** [CODAIT/node-red-contrib-model-asset-exchange#54]
Hello,
I'm having issues i stalling this on my raspberry node-red installation:

2019-05-11T11:32:47.269Z installieren : node-red-contrib-model-asset-exchange 0.2.3

2019-05-11T11:32:47.419Z npm install --no-audit --no-update-notifier --save --save-prefix="~" --production node-red-contrib-model-asset-exchange@0.2.3
2019-05-11T11:33:02.998Z [err] npm
2019-05-11T11:33:02.999Z [err]  WARN deprecated hawk@6.0.2: This module moved to @hapi/hawk. Please make sure to switch over as this distribution is no longer supported and may contain bugs and critical security issues.
2019-05-11T11:33:03.688Z [err] npm
2019-05-11T11:33:03.689Z [err]  WARN deprecated boom@4.3.1: This version has been deprecated in accordance with the hapi support policy (hapi.im/support). Please upgrade to the latest version to get the best features, bug fixes, and security patches. If you are unable to upgrade at this time, paid support is available for older versions (hapi.im/commercial).
2019-05-11T11:33:03.694Z [err] npm
2019-05-11T11:33:03.694Z [err]  WARN deprecated hoek@4.2.1: This version has been deprecated in accordance with the hapi support policy (hapi.im/support). Please upgrade to the latest version to get the best features, bug fixes, and security patches. If you are unable to upgrade at this time, paid support is available for older versions (hapi.im/commercial).
2019-05-11T11:33:03.699Z [err] npm
2019-05-11T11:33:03.700Z [err]  WARN deprecated cryptiles@3.1.4: This version has been deprecated in accordance with the hapi support policy (hapi.im/support). Please upgrade to the latest version to get the best features, bug fixes, and security patches. If you are unable to upgrade at this time, paid support is available for older versions (hapi.im/commercial).
2019-05-11T11:33:03.704Z [err] npm
2019-05-11T11:33:03.705Z [err]  WARN deprecated sntp@2.1.0: This module moved to @hapi/sntp. Please make sure to switch over as this distribution is no longer supported and may contain bugs and critical security issues.
2019-05-11T11:33:03.725Z [err] npm
2019-05-11T11:33:03.725Z [err]  WARN deprecated boom@5.2.0: This version has been deprecated in accordance with the hapi support policy (hapi.im/support). Please upgrade to the latest version to get the best features, bug fixes, and security patches. If you are unable to upgrade at this time, paid support is available for older versions (hapi.im/commercial).
2019-05-11T11:33:12.346Z [out] 
2019-05-11T11:33:12.346Z [out] > canvas@2.5.0 install /home/pi/.node-red/node_modules/canvas
2019-05-11T11:33:12.346Z [out] > node-pre-gyp install --fallback-to-build
2019-05-11T11:33:12.346Z [out] 
2019-05-11T11:33:13.622Z [err] node-pre-gyp
2019-05-11T11:33:13.623Z [err]  
2019-05-11T11:33:13.624Z [err] WARN Using request for node-pre-gyp https download
2019-05-11T11:33:13.624Z [err]  
2019-05-11T11:33:14.197Z [err] node-pre-gyp
2019-05-11T11:33:14.197Z [err]  WARN Tried to download(404): https://github.com/node-gfx/node-canvas-prebuilt/releases/download/v2.5.0/canvas-v2.5.0-node-v57-linux-glibc-arm.tar.gz 
2019-05-11T11:33:14.197Z [err] node-pre-gyp 
2019-05-11T11:33:14.197Z [err] WARN Pre-built binaries not found for canvas@2.5.0 and node@8.16.0 (node-v57 ABI, glibc) (falling back to source compile with node-gyp) 
2019-05-11T11:33:20.082Z [err] Package pixman-1 was not found in the pkg-config search path.
2019-05-11T11:33:20.082Z [err] Perhaps you should add the directory containing `pixman-1.pc'
2019-05-11T11:33:20.082Z [err] to the PKG_CONFIG_PATH environment variable
2019-05-11T11:33:20.082Z [err] No package 'pixman-1' found
2019-05-11T11:33:20.088Z [err] gyp: Call to 'pkg-config pixman-1 --libs' returned exit status 1 while in binding.gyp. while trying to load binding.gyp
2019-05-11T11:33:20.117Z [err] gyp
2019-05-11T11:33:20.117Z [err]  ERR! configure error
2019-05-11T11:33:20.117Z [err]  
2019-05-11T11:33:20.119Z [err] gyp
2019-05-11T11:33:20.119Z [err]  ERR! stack Error: `gyp` failed with exit code: 1
2019-05-11T11:33:20.119Z [err] gyp ERR!
2019-05-11T11:33:20.120Z [err]  stack
2019-05-11T11:33:20.120Z [err]      at ChildProcess.onCpExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:345:16)
2019-05-11T11:33:20.120Z [err] gyp 
2019-05-11T11:33:20.120Z [err] ERR! stack
2019-05-11T11:33:20.120Z [err]      at emitTwo (events.js:126:13)
2019-05-11T11:33:20.120Z [err] gyp
2019-05-11T11:33:20.120Z [err]  ERR! 
2019-05-11T11:33:20.120Z [err] stack     at ChildProcess.emit (events.js:214:7)
2019-05-11T11:33:20.120Z [err] gyp ERR!
2019-05-11T11:33:20.120Z [err]  stack
2019-05-11T11:33:20.121Z [err]      at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
2019-05-11T11:33:20.121Z [err] gyp
2019-05-11T11:33:20.121Z [err]  ERR! System
2019-05-11T11:33:20.121Z [err]  Linux 4.14.98-v7+
2019-05-11T11:33:20.122Z [err] gyp
2019-05-11T11:33:20.122Z [err]  ERR! 
2019-05-11T11:33:20.122Z [err] command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "--fallback-to-build" "--module=/home/pi/.node-red/node_modules/canvas/build/Release/canvas.node" "--module_name=canvas" "--module_path=/home/pi/.node-red/node_modules/canvas/build/Release" "--napi_version=4" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=node-v57"
2019-05-11T11:33:20.122Z [err] gyp
2019-05-11T11:33:20.122Z [err]  ERR!
2019-05-11T11:33:20.122Z [err]  cwd /home/pi/.node-red/node_modules/canvas
2019-05-11T11:33:20.123Z [err] gyp
2019-05-11T11:33:20.123Z [err]  ERR! 
2019-05-11T11:33:20.123Z [err] node -v v8.16.0
2019-05-11T11:33:20.123Z [err] gyp 
2019-05-11T11:33:20.123Z [err] ERR! 
2019-05-11T11:33:20.123Z [err] node-gyp -v v3.8.0
2019-05-11T11:33:20.123Z [err] gyp
2019-05-11T11:33:20.123Z [err]  ERR! 
2019-05-11T11:33:20.123Z [err] not ok 
2019-05-11T11:33:20.132Z [err] node-pre-gyp
2019-05-11T11:33:20.134Z [err]  ERR! build error 
2019-05-11T11:33:20.134Z [err] node-pre-gyp
2019-05-11T11:33:20.134Z [err]  ERR! stack
2019-05-11T11:33:20.135Z [err]  Error: Failed to execute '/usr/bin/node /usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/home/pi/.node-red/node_modules/canvas/build/Release/canvas.node --module_name=canvas --module_path=/home/pi/.node-red/node_modules/canvas/build/Release --napi_version=4 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v57' (1)
2019-05-11T11:33:20.135Z [err] node-pre-gyp
2019-05-11T11:33:20.135Z [err]  ERR! 
2019-05-11T11:33:20.135Z [err] stack     at ChildProcess.<anonymous> (/home/pi/.node-red/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
2019-05-11T11:33:20.135Z [err] node-pre-gyp 
2019-05-11T11:33:20.135Z [err] ERR! stack
2019-05-11T11:33:20.135Z [err]      at emitTwo (events.js:126:13)
2019-05-11T11:33:20.135Z [err] node-pre-gyp
2019-05-11T11:33:20.135Z [err]  ERR!
2019-05-11T11:33:20.135Z [err]  stack     at ChildProcess.emit (events.js:214:7)
2019-05-11T11:33:20.135Z [err] node-pre-gyp 
2019-05-11T11:33:20.136Z [err] ERR! 
2019-05-11T11:33:20.136Z [err] stack     at maybeClose (internal/child_process.js:915:16)
2019-05-11T11:33:20.136Z [err] node-pre-gyp
2019-05-11T11:33:20.136Z [err]  ERR!
2019-05-11T11:33:20.136Z [err]  stack
2019-05-11T11:33:20.136Z [err]      at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
2019-05-11T11:33:20.137Z [err] node-pre-gyp
2019-05-11T11:33:20.137Z [err]  ERR! System
2019-05-11T11:33:20.137Z [err]  Linux 4.14.98-v7+
2019-05-11T11:33:20.137Z [err] node-pre-gyp
2019-05-11T11:33:20.137Z [err]  ERR!
2019-05-11T11:33:20.137Z [err]  command
2019-05-11T11:33:20.138Z [err]  "/usr/bin/node" "/home/pi/.node-red/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
2019-05-11T11:33:20.138Z [err] node-pre-gyp 
2019-05-11T11:33:20.138Z [err] ERR! 
2019-05-11T11:33:20.138Z [err] cwd /home/pi/.node-red/node_modules/canvas
2019-05-11T11:33:20.138Z [err] node-pre-gyp 
2019-05-11T11:33:20.138Z [err] ERR! node -v
2019-05-11T11:33:20.138Z [err]  v8.16.0
2019-05-11T11:33:20.138Z [err] node-pre-gyp
2019-05-11T11:33:20.139Z [err]  ERR!
2019-05-11T11:33:20.139Z [err]  node-pre-gyp -v v0.11.0
2019-05-11T11:33:20.139Z [err] node-pre-gyp
2019-05-11T11:33:20.139Z [err]  ERR!
2019-05-11T11:33:20.139Z [err]  not ok
2019-05-11T11:33:20.139Z [err]  
2019-05-11T11:33:20.140Z [out] Failed to execute '/usr/bin/node /usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/home/pi/.node-red/node_modules/canvas/build/Release/canvas.node --module_name=canvas --module_path=/home/pi/.node-red/node_modules/canvas/build/Release --napi_version=4 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v57' (1)
2019-05-11T11:33:22.495Z [err] npm
2019-05-11T11:33:22.495Z [err]  WARN node-red-project@0.0.1 No repository field.
2019-05-11T11:33:22.495Z [err] npm WARN
2019-05-11T11:33:22.495Z [err]  node-red-project@0.0.1 No license field.
2019-05-11T11:33:22.496Z [err] 
2019-05-11T11:33:22.505Z [err] npm
2019-05-11T11:33:22.506Z [err]  ERR! code ELIFECYCLE
2019-05-11T11:33:22.506Z [err] npm
2019-05-11T11:33:22.506Z [err]  ERR! errno
2019-05-11T11:33:22.506Z [err]  1
2019-05-11T11:33:22.507Z [err] npm
2019-05-11T11:33:22.507Z [err]  ERR! canvas@2.5.0 install: `node-pre-gyp install --fallback-to-build`
2019-05-11T11:33:22.507Z [err] npm ERR!
2019-05-11T11:33:22.507Z [err]  Exit status 1
2019-05-11T11:33:22.508Z [err] npm
2019-05-11T11:33:22.508Z [err]  ERR!
2019-05-11T11:33:22.508Z [err]  
2019-05-11T11:33:22.508Z [err] npm 
2019-05-11T11:33:22.508Z [err] ERR! Failed at the canvas@2.5.0 install script.
2019-05-11T11:33:22.508Z [err] npm ERR!
2019-05-11T11:33:22.508Z [err]  This is probably not a problem with npm. There is likely additional logging output above.
2019-05-11T11:33:22.556Z [err] 
2019-05-11T11:33:22.557Z [err] npm ERR! A complete log of this run can be found in:
2019-05-11T11:33:22.557Z [err] npm 
2019-05-11T11:33:22.557Z [err] ERR!     /home/pi/.npm/_logs/2019-05-11T11_33_22_532Z-debug.log
2019-05-11T11:33:22.581Z rc=1

-----------------------------------------------------------
2019-05-11T11:38:23.584Z installieren : node-red-contrib-model-asset-exchange 0.2.3

2019-05-11T11:38:23.674Z npm install --no-audit --no-update-notifier --save --save-prefix="~" --production node-red-contrib-model-asset-exchange@0.2.3
2019-05-11T11:38:38.515Z [err] npm
2019-05-11T11:38:38.516Z [err]  WARN deprecated hawk@6.0.2: This module moved to @hapi/hawk. Please make sure to switch over as this distribution is no longer supported and may contain bugs and critical security issues.
2019-05-11T11:38:38.981Z [err] npm
2019-05-11T11:38:38.982Z [err]  WARN deprecated hoek@4.2.1: This version has been deprecated in accordance with the hapi support policy (hapi.im/support). Please upgrade to the latest version to get the best features, bug fixes, and security patches. If you are unable to upgrade at this time, paid support is available for older versions (hapi.im/commercial).
2019-05-11T11:38:38.987Z [err] npm
2019-05-11T11:38:38.987Z [err]  WARN deprecated boom@4.3.1: This version has been deprecated in accordance with the hapi support policy (hapi.im/support). Please upgrade to the latest version to get the best features, bug fixes, and security patches. If you are unable to upgrade at this time, paid support is available for older versions (hapi.im/commercial).
2019-05-11T11:38:38.997Z [err] npm
2019-05-11T11:38:38.997Z [err]  WARN deprecated cryptiles@3.1.4: This version has been deprecated in accordance with the hapi support policy (hapi.im/support). Please upgrade to the latest version to get the best features, bug fixes, and security patches. If you are unable to upgrade at this time, paid support is available for older versions (hapi.im/commercial).
2019-05-11T11:38:39.002Z [err] npm
2019-05-11T11:38:39.003Z [err]  WARN deprecated
2019-05-11T11:38:39.006Z [err]  sntp@2.1.0: This module moved to @hapi/sntp. Please make sure to switch over as this distribution is no longer supported and may contain bugs and critical security issues.
2019-05-11T11:38:39.024Z [err] npm
2019-05-11T11:38:39.024Z [err]  WARN deprecated boom@5.2.0: This version has been deprecated in accordance with the hapi support policy (hapi.im/support). Please upgrade to the latest version to get the best features, bug fixes, and security patches. If you are unable to upgrade at this time, paid support is available for older versions (hapi.im/commercial).
2019-05-11T11:38:47.145Z [out] 
2019-05-11T11:38:47.145Z [out] > canvas@2.5.0 install /home/pi/.node-red/node_modules/canvas
2019-05-11T11:38:47.145Z [out] > node-pre-gyp install --fallback-to-build
2019-05-11T11:38:47.145Z [out] 
2019-05-11T11:38:48.335Z [err] node-pre-gyp
2019-05-11T11:38:48.337Z [err]  
2019-05-11T11:38:48.337Z [err] WARN
2019-05-11T11:38:48.337Z [err]  Using request for node-pre-gyp https download
2019-05-11T11:38:48.337Z [err]  
2019-05-11T11:38:49.178Z [err] node-pre-gyp
2019-05-11T11:38:49.178Z [err]  WARN Tried to download(404): https://github.com/node-gfx/node-canvas-prebuilt/releases/download/v2.5.0/canvas-v2.5.0-node-v57-linux-glibc-arm.tar.gz 
2019-05-11T11:38:49.178Z [err] node-pre-gyp
2019-05-11T11:38:49.178Z [err]  WARN 
2019-05-11T11:38:49.178Z [err] Pre-built binaries not found for canvas@2.5.0 and node@8.16.0 (node-v57 ABI, glibc) (falling back to source compile with node-gyp) 
2019-05-11T11:38:52.838Z [err] Package pixman-1 was not found in the pkg-config search path.
2019-05-11T11:38:52.838Z [err] Perhaps you should add the directory containing `pixman-1.pc'
2019-05-11T11:38:52.838Z [err] to the PKG_CONFIG_PATH environment variable
2019-05-11T11:38:52.838Z [err] No package 'pixman-1' found
2019-05-11T11:38:52.838Z [err] gyp: Call to 'pkg-config pixman-1 --libs' returned exit status 1 while in binding.gyp. while trying to load binding.gyp
2019-05-11T11:38:52.868Z [err] gyp
2019-05-11T11:38:52.876Z [err]  ERR! configure error 
2019-05-11T11:38:52.876Z [err] gyp ERR! stack Error: `gyp` failed with exit code: 1
2019-05-11T11:38:52.876Z [err] gyp ERR! stack     at ChildProcess.onCpExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:345:16)
2019-05-11T11:38:52.876Z [err] gyp ERR! stack     at emitTwo (events.js:126:13)
2019-05-11T11:38:52.876Z [err] gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
2019-05-11T11:38:52.876Z [err] gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
2019-05-11T11:38:52.876Z [err] gyp ERR! System Linux 4.14.98-v7+
2019-05-11T11:38:52.876Z [err] gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "--fallback-to-build" "--module=/home/pi/.node-red/node_modules/canvas/build/Release/canvas.node" "--module_name=canvas" "--module_path=/home/pi/.node-red/node_modules/canvas/build/Release" "--napi_version=4" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=node-v57"
2019-05-11T11:38:52.876Z [err] gyp ERR! cwd /home/pi/.node-red/node_modules/canvas
2019-05-11T11:38:52.876Z [err] gyp ERR! node -v v8.16.0
2019-05-11T11:38:52.876Z [err] gyp ERR! node-gyp -v v3.8.0
2019-05-11T11:38:52.876Z [err] gyp ERR! not ok 
2019-05-11T11:38:52.888Z [err] node-pre-gyp ERR! build error 
2019-05-11T11:38:52.888Z [err] node-pre-gyp ERR! stack Error: Failed to execute '/usr/bin/node /usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/home/pi/.node-red/node_modules/canvas/build/Release/canvas.node --module_name=canvas --module_path=/home/pi/.node-red/node_modules/canvas/build/Release --napi_version=4 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v57' (1)
2019-05-11T11:38:52.888Z [err] node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/home/pi/.node-red/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
2019-05-11T11:38:52.888Z [err] node-pre-gyp ERR! stack     at emitTwo (events.js:126:13)
2019-05-11T11:38:52.888Z [err] node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
2019-05-11T11:38:52.888Z [err] node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:915:16)
2019-05-11T11:38:52.888Z [err] node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
2019-05-11T11:38:52.888Z [err] node-pre-gyp ERR! System Linux 4.14.98-v7+
2019-05-11T11:38:52.888Z [err] node-pre-gyp ERR! command "/usr/bin/node" "/home/pi/.node-red/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
2019-05-11T11:38:52.888Z [err] node-pre-gyp ERR! cwd /home/pi/.node-red/node_modules/canvas
2019-05-11T11:38:52.888Z [err] node-pre-gyp 
2019-05-11T11:38:52.892Z [err] ERR! node -v v8.16.0
2019-05-11T11:38:52.892Z [err] node-pre-gyp ERR! node-pre-gyp -v v0.11.0
2019-05-11T11:38:52.892Z [err] node-pre-gyp ERR! not ok 
2019-05-11T11:38:52.893Z [out] Failed to execute '/usr/bin/node /usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/home/pi/.node-red/node_modules/canvas/build/Release/canvas.node --module_name=canvas --module_path=/home/pi/.node-red/node_modules/canvas/build/Release --napi_version=4 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v57' (1)
2019-05-11T11:38:55.099Z [err] npm
2019-05-11T11:38:55.100Z [err]  WARN node-red-project@0.0.1 No repository field.
2019-05-11T11:38:55.100Z [err] npm WARN
2019-05-11T11:38:55.100Z [err]  node-red-project@0.0.1 No license field.
2019-05-11T11:38:55.100Z [err] 
2019-05-11T11:38:55.105Z [err] npm
2019-05-11T11:38:55.106Z [err]  ERR! code ELIFECYCLE
2019-05-11T11:38:55.106Z [err] npm
2019-05-11T11:38:55.106Z [err]  ERR! errno 1
2019-05-11T11:38:55.107Z [err] npm
2019-05-11T11:38:55.107Z [err]  ERR! canvas@2.5.0 install: `node-pre-gyp install --fallback-to-build`
2019-05-11T11:38:55.107Z [err] npm
2019-05-11T11:38:55.107Z [err]  ERR!
2019-05-11T11:38:55.107Z [err]  Exit status 1
2019-05-11T11:38:55.108Z [err] npm
2019-05-11T11:38:55.108Z [err]  ERR!
2019-05-11T11:38:55.108Z [err]  
2019-05-11T11:38:55.108Z [err] npm
2019-05-11T11:38:55.108Z [err]  ERR!
2019-05-11T11:38:55.108Z [err]  Failed at the canvas@2.5.0 install script.
2019-05-11T11:38:55.108Z [err] npm 
2019-05-11T11:38:55.108Z [err] ERR! This is probably not a problem with npm. There is likely additional logging output above.
2019-05-11T11:38:55.188Z [err] 
2019-05-11T11:38:55.188Z [err] npm ERR! A complete log of this run can be found in:
2019-05-11T11:38:55.188Z [err] npm 
2019-05-11T11:38:55.188Z [err] ERR!     /home/pi/.npm/_logs/2019-05-11T11_38_55_128Z-debug.log
2019-05-11T11:38:55.209Z rc=1

**Comment by ptitzler** [comment]
This appears to be a duplicate of #52. We are working on a fix that removes the breaking dependency.  Please install version 0.2.0 for now. Thanks!

**Comment by martinschki** [comment]
I tried to install 0.2.0 and according to npm it seemed successful but the nodes are not showing up in node-red
Could you please assist? What do I need to provide?
Thank you

**Comment by ptitzler** [comment]
Most certainly! Easiest/fasted way for us to help if you could join http://ibm.biz/max-slack (node-red channel). If you prefer not too, that's fine.

Can you provide the following information:
 - Installed Node-Red version
 - Is the `node-red-contrib-model-asset-exchange` module displayed in the Node-RED editor (under "User Settings" > "Palette" > "Nodes"
 - Are there any errors displayed in the Node-RED log?

**Comment by kastentx** [comment]
@martinschki we've just published a new version `0.2.4` that got rid of the dependencies causing this error. 

You should now be able to install the most recent update and try out the new visualization features. Let us know (either here, or in the [Slack channel](http://ibm.biz/max-slack)) if you run into any further issues and we'll be happy to help

**Comment by martinschki** [comment]
0.2.4 is working
thank you!!
